version: "3"

services:
  aac_build:
    build: .
    volumes:
      - ./:/AAC
    working_dir: /AAC
    command: make build

  aac_test:
    build: .
    volumes:
    - ./:/AAC
    working_dir: /AAC
    command: make buildtest
