// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Core.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender               uint32   `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             uint32   `protobuf:"varint,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8d6e0ab9231f09, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetSender() uint32 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *Message) GetReceiver() uint32 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Zero struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zero) Reset()         { *m = Zero{} }
func (m *Zero) String() string { return proto.CompactTextString(m) }
func (*Zero) ProtoMessage()    {}
func (*Zero) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c8d6e0ab9231f09, []int{1}
}

func (m *Zero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zero.Unmarshal(m, b)
}
func (m *Zero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zero.Marshal(b, m, deterministic)
}
func (m *Zero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zero.Merge(m, src)
}
func (m *Zero) XXX_Size() int {
	return xxx_messageInfo_Zero.Size(m)
}
func (m *Zero) XXX_DiscardUnknown() {
	xxx_messageInfo_Zero.DiscardUnknown(m)
}

var xxx_messageInfo_Zero proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Zero)(nil), "Zero")
}

func init() { proto.RegisterFile("Core.proto", fileDescriptor_6c8d6e0ab9231f09) }

var fileDescriptor_6c8d6e0ab9231f09 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x3d, 0xcf, 0x82, 0x40,
	0x10, 0x84, 0xdf, 0xe3, 0xc5, 0x03, 0xd7, 0x8f, 0xe2, 0x0a, 0x73, 0xa1, 0xba, 0x50, 0x91, 0x98,
	0x60, 0xa2, 0xff, 0x40, 0x6a, 0x2d, 0xb0, 0xa3, 0x3b, 0xd8, 0x8d, 0xa1, 0x61, 0xc9, 0x42, 0xfc,
	0xfd, 0xc6, 0x0b, 0xda, 0x3d, 0x4f, 0x66, 0x92, 0x19, 0x80, 0x8a, 0x85, 0xca, 0x51, 0x78, 0xe6,
	0xdc, 0x43, 0x72, 0xa3, 0x69, 0xf2, 0x4f, 0x32, 0x7b, 0x88, 0x7a, 0xb4, 0xca, 0xa9, 0x62, 0x5d,
	0x47, 0x3d, 0x9a, 0x03, 0xe8, 0x89, 0x06, 0x24, 0xb1, 0x91, 0x53, 0xc5, 0xae, 0x5e, 0xcc, 0x64,
	0x90, 0x0a, 0x75, 0xd4, 0xbf, 0x48, 0xec, 0x7f, 0x48, 0x7e, 0x6e, 0x0c, 0xc4, 0xe8, 0x67, 0x6f,
	0x63, 0xa7, 0x8a, 0x6d, 0x1d, 0x38, 0xd7, 0x10, 0x37, 0x24, 0x7c, 0x3e, 0x42, 0x72, 0x67, 0xa4,
	0x8a, 0x07, 0xe3, 0x60, 0xf3, 0xa0, 0x01, 0xbf, 0xcb, 0x69, 0xb9, 0x50, 0xb6, 0x2a, 0x3f, 0xd5,
	0xfc, 0xef, 0x9a, 0x36, 0xda, 0xfb, 0xee, 0x34, 0xb6, 0xad, 0x0e, 0x47, 0x2f, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa2, 0xe9, 0x8d, 0x65, 0xb6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeConClient is the client API for NodeCon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeConClient interface {
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Zero, error)
}

type nodeConClient struct {
	cc *grpc.ClientConn
}

func NewNodeConClient(cc *grpc.ClientConn) NodeConClient {
	return &nodeConClient{cc}
}

func (c *nodeConClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Zero, error) {
	out := new(Zero)
	err := c.cc.Invoke(ctx, "/NodeCon/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeConServer is the server API for NodeCon service.
type NodeConServer interface {
	SendMessage(context.Context, *Message) (*Zero, error)
}

// UnimplementedNodeConServer can be embedded to have forward compatible implementations.
type UnimplementedNodeConServer struct {
}

func (*UnimplementedNodeConServer) SendMessage(ctx context.Context, req *Message) (*Zero, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

func RegisterNodeConServer(s *grpc.Server, srv NodeConServer) {
	s.RegisterService(&_NodeCon_serviceDesc, srv)
}

func _NodeCon_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeConServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeCon/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeConServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeCon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "NodeCon",
	HandlerType: (*NodeConServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _NodeCon_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Core.proto",
}
